/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REMTOP_H_RPCGEN
#define _REMTOP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXHOSTS 10

struct key_input {
	int on_press;
	int keycode;
	int x;
	int y;
};
typedef struct key_input key_input;


struct mouse_input {
	int x;
	int y;
	int button;
	int on_press;
	int button_event;
};
typedef struct mouse_input mouse_input;


struct image_input {
	int init;
	char host[1024];
};
typedef struct image_input image_input;


#define KEYBOARDPROG 22855
#define KEYBOARDVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define KEYBOARD 1
extern  int * keyboard_1(key_input *, CLIENT *);
extern  int * keyboard_1_svc(key_input *, struct svc_req *);
extern int keyboardprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define KEYBOARD 1
extern  int * keyboard_1();
extern  int * keyboard_1_svc();
extern int keyboardprog_1_freeresult ();
#endif /* K&R C */

#define MOUSEPROG 22856
#define MOUSEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MOUSE 1
extern  int * mouse_1(mouse_input *, CLIENT *);
extern  int * mouse_1_svc(mouse_input *, struct svc_req *);
extern int mouseprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MOUSE 1
extern  int * mouse_1();
extern  int * mouse_1_svc();
extern int mouseprog_1_freeresult ();
#endif /* K&R C */

#define IMAGEPROG 22857
#define IMAGEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define IMAGE 1
extern  int * image_1(image_input *, CLIENT *);
extern  int * image_1_svc(image_input *, struct svc_req *);
extern int imageprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IMAGE 1
extern  int * image_1();
extern  int * image_1_svc();
extern int imageprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_key_input (XDR *, key_input*);
extern  bool_t xdr_key_input (XDR *, key_input*);
extern  bool_t xdr_mouse_input (XDR *, mouse_input*);
extern  bool_t xdr_mouse_input (XDR *, mouse_input*);
extern  bool_t xdr_image_input (XDR *, image_input*);
extern  bool_t xdr_image_input (XDR *, image_input*);

#else /* K&R C */
extern bool_t xdr_key_input ();
extern bool_t xdr_key_input ();
extern bool_t xdr_mouse_input ();
extern bool_t xdr_mouse_input ();
extern bool_t xdr_image_input ();
extern bool_t xdr_image_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REMTOP_H_RPCGEN */
