/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "remtop.h"

bool_t
xdr_key_input (XDR *xdrs, key_input *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->on_press))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->keycode))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->on_press);
			IXDR_PUT_LONG(buf, objp->keycode);
			IXDR_PUT_LONG(buf, objp->x);
			IXDR_PUT_LONG(buf, objp->y);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->on_press))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->keycode))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
		} else {
			objp->on_press = IXDR_GET_LONG(buf);
			objp->keycode = IXDR_GET_LONG(buf);
			objp->x = IXDR_GET_LONG(buf);
			objp->y = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->on_press))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->keycode))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_mouse_input (XDR *xdrs, mouse_input *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->button))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->on_press))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->button_event))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->x);
			IXDR_PUT_LONG(buf, objp->y);
			IXDR_PUT_LONG(buf, objp->button);
			IXDR_PUT_LONG(buf, objp->on_press);
			IXDR_PUT_LONG(buf, objp->button_event);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 5 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->x))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->y))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->button))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->on_press))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->button_event))
				 return FALSE;
		} else {
			objp->x = IXDR_GET_LONG(buf);
			objp->y = IXDR_GET_LONG(buf);
			objp->button = IXDR_GET_LONG(buf);
			objp->on_press = IXDR_GET_LONG(buf);
			objp->button_event = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->button))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->on_press))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->button_event))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_image_input (XDR *xdrs, image_input *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->init))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->host, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
