/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SCREENSHOT_H_RPCGEN
#define _SCREENSHOT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct input_data {
	struct {
		u_int input_data_len;
		char *input_data_val;
	} input_data;
};
typedef struct input_data input_data;


#define SCREENSHOTPROG 22855
#define SCREENSHOTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SCREENSHOT 1
extern  int * screenshot_1(input_data *, CLIENT *);
extern  int * screenshot_1_svc(input_data *, struct svc_req *);
extern int screenshotprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SCREENSHOT 1
extern  int * screenshot_1();
extern  int * screenshot_1_svc();
extern int screenshotprog_1_freeresult ();
#endif /* K&R C */

#define DELETEIMAGEPROG 22856
#define DELETEIMAGEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DELETEIMAGE 1
extern  int * deleteimage_1(void *, CLIENT *);
extern  int * deleteimage_1_svc(void *, struct svc_req *);
extern int deleteimageprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DELETEIMAGE 1
extern  int * deleteimage_1();
extern  int * deleteimage_1_svc();
extern int deleteimageprog_1_freeresult ();
#endif /* K&R C */

#define REFRESHDISPLAYPROG 22857
#define REFRESHDISPLAYVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REFRESHDISPLAY 1
extern  int * refreshdisplay_1(void *, CLIENT *);
extern  int * refreshdisplay_1_svc(void *, struct svc_req *);
extern int refreshdisplayprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REFRESHDISPLAY 1
extern  int * refreshdisplay_1();
extern  int * refreshdisplay_1_svc();
extern int refreshdisplayprog_1_freeresult ();
#endif /* K&R C */

#define INITDISPLAYPROG 22858
#define INITDISPLAYVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INITDISPLAY 1
extern  int * initdisplay_1(void *, CLIENT *);
extern  int * initdisplay_1_svc(void *, struct svc_req *);
extern int initdisplayprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INITDISPLAY 1
extern  int * initdisplay_1();
extern  int * initdisplay_1_svc();
extern int initdisplayprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_input_data (XDR *, input_data*);
extern  bool_t xdr_input_data (XDR *, input_data*);

#else /* K&R C */
extern bool_t xdr_input_data ();
extern bool_t xdr_input_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SCREENSHOT_H_RPCGEN */
