screencap: screencap.c
	gcc -Wall -g -ansi -pedantic    screencap.c   -o screencap -I/usr/include/glib-2.0/ -I/usr/include/gtk-2.0/ -I/usr/lib/glib-2.0/include/ -I/usr/include/cairo/ -I/usr/include/pango-1.0/ -I/usr/lib/gtk-2.0/include/ -I/usr/include/gdk-pixbuf-2.0/ `pkg-config --cflags gtk+-2.0` `pkg-config --libs gtk+-2.0`
