/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "screenshot.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
screenshotprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		input_data screenshot_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SCREENSHOT:
		_xdr_argument = (xdrproc_t) xdr_input_data;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) screenshot_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
deleteimageprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int fill;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case DELETEIMAGE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) deleteimage_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
refreshdisplayprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int fill;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REFRESHDISPLAY:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) refreshdisplay_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
initdisplayprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int fill;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INITDISPLAY:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) initdisplay_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SCREENSHOTPROG, SCREENSHOTVERS);
	pmap_unset (DELETEIMAGEPROG, DELETEIMAGEVERS);
	pmap_unset (REFRESHDISPLAYPROG, REFRESHDISPLAYVERS);
	pmap_unset (INITDISPLAYPROG, INITDISPLAYVERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SCREENSHOTPROG, SCREENSHOTVERS, screenshotprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SCREENSHOTPROG, SCREENSHOTVERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, DELETEIMAGEPROG, DELETEIMAGEVERS, deleteimageprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DELETEIMAGEPROG, DELETEIMAGEVERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, REFRESHDISPLAYPROG, REFRESHDISPLAYVERS, refreshdisplayprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (REFRESHDISPLAYPROG, REFRESHDISPLAYVERS, udp).");
		exit(1);
	}
	if (!svc_register(transp, INITDISPLAYPROG, INITDISPLAYVERS, initdisplayprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (INITDISPLAYPROG, INITDISPLAYVERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SCREENSHOTPROG, SCREENSHOTVERS, screenshotprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SCREENSHOTPROG, SCREENSHOTVERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, DELETEIMAGEPROG, DELETEIMAGEVERS, deleteimageprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DELETEIMAGEPROG, DELETEIMAGEVERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, REFRESHDISPLAYPROG, REFRESHDISPLAYVERS, refreshdisplayprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (REFRESHDISPLAYPROG, REFRESHDISPLAYVERS, tcp).");
		exit(1);
	}
	if (!svc_register(transp, INITDISPLAYPROG, INITDISPLAYVERS, initdisplayprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (INITDISPLAYPROG, INITDISPLAYVERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
