/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "soundserver.h"

bool_t
xdr_input_data (XDR *xdrs, input_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->buffer, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_control_data (XDR *xdrs, control_data *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->init))
		 return FALSE;
	return TRUE;
}
